# Generated by Django 3.2.9 on 2022-01-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(max_length=600, null=True)),
                ('price', models.FloatField()),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
