# Generated by Django 3.2.9 on 2022-01-17 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pageb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery1',
            name='price',
        ),
    ]
