# Generated by Django 3.2.9 on 2022-01-19 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pageb', '0002_remove_gallery1_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery1',
            new_name='Prod',
        ),
    ]
