# Generated by Django 3.2.9 on 2022-01-20 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pageb', '0003_rename_gallery1_prod'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prod',
            new_name='Gallery1',
        ),
    ]
