# Generated by Django 3.2.9 on 2022-01-21 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pageb', '0006_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery3c',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Image3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('default', models.BooleanField(default=False)),
                ('gallery3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pageb.gallery2')),
            ],
        ),
    ]
