# Generated by Django 3.2.12 on 2022-03-20 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pageb', '0007_gallery3c_image3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery3c',
        ),
        migrations.RemoveField(
            model_name='image',
            name='gallery2',
        ),
        migrations.RemoveField(
            model_name='image3',
            name='gallery3',
        ),
        migrations.DeleteModel(
            name='Gallery2',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
