# Generated by Django 3.2.16 on 2022-12-02 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pageb', '0009_auto_20221202_1724'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Kategoria',
        ),
        migrations.RenameField(
            model_name='gallery1',
            old_name='categoria',
            new_name='kategoria',
        ),
    ]
