# Generated by Django 3.2.16 on 2022-12-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageb', '0012_alter_opinion_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
