# Generated by Django 3.2.16 on 2022-12-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageb', '0013_opinion_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='name',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
