# Generated by Django 3.2.16 on 2022-12-19 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pageb', '0014_alter_opinion_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='gallery1',
            name='kategoria',
        ),
        migrations.DeleteModel(
            name='Image3',
        ),
        migrations.RenameModel(
            old_name='Kategoria',
            new_name='Category',
        ),
        migrations.DeleteModel(
            name='Gallery1',
        ),
        migrations.AddField(
            model_name='gallery',
            name='kategoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pageb.category'),
        ),
    ]
